### ISSUE TITLE
Problems after update to version 0.3.0

### ISSUE THREAD

**Issue by hermannw** [GermanBluefox/node-red-vis#11]
After updating to version 0.3.0 the following problems occur:
When I enter "http://192.168.1.xxx:1880/vis/edit.html#metro" all I see is a blue bar at the top of the window.
When I enter "http://192.168.1.xxx:1880/vis/index.html#metro" I only get "No connection to Server"

Any ideas?

**Comment by GermanBluefox** [comment]
I tried just now to install **node-red** + **noder-red-vis** from scratch and it works.
To **node-red-vis** was added new package **iobroker.web**. It looks like you don't have it.
Try to delete **node-red-vis** directory and install it anew.

**Comment by hermannw** [comment]
iobroker.web is installed.
![vis1](https://cloud.githubusercontent.com/assets/5613181/10909610/0a165102-8200-11e5-824b-0b4a3732b3b3.JPG)
![vis2](https://cloud.githubusercontent.com/assets/5613181/10909613/0d995f68-8200-11e5-801d-d6540a6ce6d4.JPG)
I also updated node-red to the latest version.
I will try to delete and reinstall node-red-vis.

**Comment by hermannw** [comment]
Nope. No luck. Deleted the node-red-vis directory and reinstalled it.
Same output.
Here are the messages that came up during install.

---

root@raspberrypi:/usr/local/lib/node_modules# npm install node-red-vis
|

> utf-8-validate@1.2.1 install /usr/local/lib/node_modules/node-red-vis/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.24"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/node-red-vis/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate/.node-gyp"
make: Entering directory '/usr/local/lib/node_modules/node-red-vis/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory '/usr/local/lib/node_modules/node-red-vis/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate/build'
npm WARN engine hawk@3.1.0: wanted: {"node":">=0.10.32"} (current: {"node":"0.10.24","npm":"2.10.0"})

> bufferutil@1.2.1 install /usr/local/lib/node_modules/node-red-vis/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.24"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/node-red-vis/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil/.node-gyp"
make: Entering directory '/usr/local/lib/node_modules/node-red-vis/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
make: Leaving directory '/usr/local/lib/node_modules/node-red-vis/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil/build'
npm WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.24","npm":"2.10.0"})
npm WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.24","npm":"2.10.0"})
npm WARN engine cryptiles@2.0.5: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.24","npm":"2.10.0"})

> bufferutil@1.2.1 install /usr/local/lib/node_modules/node-red-vis/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.24"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/node-red-vis/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil/.node-gyp"
make: Entering directory '/usr/local/lib/node_modules/node-red-vis/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
make: Leaving directory '/usr/local/lib/node_modules/node-red-vis/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil/build'

> utf-8-validate@1.2.1 install /usr/local/lib/node_modules/node-red-vis/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.10.24"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/node-red-vis/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate/.node-gyp"
make: Entering directory '/usr/local/lib/node_modules/node-red-vis/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory '/usr/local/lib/node_modules/node-red-vis/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate/build'

> iobroker.vis@0.7.5 install /usr/local/lib/node_modules/node-red-vis/node_modules/iobroker.vis
> node main.js --install
> 
> node-red-vis@0.3.0 install /usr/local/lib/node_modules/node-red-vis
> node node_modules/iobroker.vis/lib/install.js

node-red-vis@0.3.0 node-red-vis
├── iobroker.vis-keyboard@0.0.2
├── iobroker.vis-fancyswitch@0.1.0
├── iobroker.vis-bars@0.1.1
├── iobroker.vis-colorpicker@0.1.1
├── iobroker.vis-hqwidgets@0.2.1
├── iobroker.vis-jqui-mfd@0.1.0
├── iobroker.vis-lcars@0.1.6
├── iobroker.vis-rgraph@0.0.2
├── iobroker.vis-timeandweather@0.0.2
├── iobroker.vis-plumb@0.1.6
├── iobroker.vis-metro@0.1.9
├── iobroker.web@1.1.1 (connect-flash@0.1.1, xtend@4.0.1, cookie-parser@1.4.0, passport-local@1.0.0, iobroker.simple-api@1.0.0, iobroker.socketio@1.0.0, passport@0.2.2, express-session@1.12.1, body-parser@1.14.1, express@4.13.3, request@2.65.0)
├── socket.io@1.3.7 (debug@2.1.0, has-binary-data@0.1.3, socket.io-adapter@0.3.1, socket.io-parser@2.2.4, engine.io@1.5.4, socket.io-client@1.3.7)
└── iobroker.vis@0.7.5
root@raspberrypi:/usr/local/lib/node_modules#

---

**Comment by hermannw** [comment]
After restarting node-red three more times I got it working. Sorta...
The editor works in Firefox and Chrome but when I try to open the ...index.html... page FF still shows "No connection to Server". It works in Chrome though.

But there is another thing that does not work:
The light bulb "ON" icon does not show up.
![vis3](https://cloud.githubusercontent.com/assets/5613181/10917591/36a3f284-8227-11e5-9378-0ac0c09446a1.JPG)
 Four light bulbs. The second light bulb from the left should be on.

Maybe the icon is missing?
![vis4](https://cloud.githubusercontent.com/assets/5613181/10917632/655a6a4a-8227-11e5-86af-b32fed0a0194.JPG)
I am not really sure where the /vis/img/ path points to. If I click on the blue rectangle the File Manager opens and shows "Not exists".

With 'find / -name "bulb_*.png"' the combination of bulb_on.png and bulb_off.png was found multiple times on the HD but always together. So it seems like the icon is not missing...

**Comment by GermanBluefox** [comment]
Try to clear the browser cache.

**Comment by hermannw** [comment]
Solved.
"Accidentally" I clicked on the place where the icon was supposed to be and all of a sudden it showed up.... Off to the next adventure!

Thanks for the help!
