### ISSUE TITLE
Error during update to 0.4.1

### ISSUE THREAD

**Issue by hermannw** [GermanBluefox/node-red-vis#12]
This error comes up when I try to do an update:

npm ERR! Linux 4.1.19+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "update" "node-red-vis"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/ioBroker.vis-google-fonts
npm ERR! 404
npm ERR! 404 'ioBroker.vis-google-fonts' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm ERR! 404
npm ERR! 404  1. name can no longer contain capital letters
npm ERR! 404 It was specified as a dependency of 'node-red-vis'

**Comment by GermanBluefox** [comment]
Thanks. Please try again with new version.

**Comment by hermannw** [comment]
Thank you! It works now.
