### ISSUE TITLE
Error building.  I have VS 2915 Community Edition Installed...

### ISSUE THREAD

**Issue by gillerman** [GermanBluefox/node-red-vis#13]
I get an error when building win_delay hook.cc  Any help would be appreciated.  Thank you in advance.

 
  ursaNative.cc
  win_delay_load_hook.cc
c:\users\john\.node-gyp\4.6.0\include\node\v8.h(18): fatal error C1083: Cannot
open include file: 'stddef.h': No such file or directory (compiling source file
 ..\src\ursaNative.cc) [C:\Users\John\node_modules\node-red-vis\node_modules\io
broker.web\node_modules\letsencrypt\node_modules\rsa-compat\node_modules\ursa\b
uild\ursaNative.vcxproj]
C:\Program Files (x86)\Windows Kits\8.1\Include\um\winnt.h(31): fatal error C10
83: Cannot open include file: 'ctype.h': No such file or directory (compiling s
ource file C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\w
in_delay_load_hook.cc) [C:\Users\John\node_modules\node-red-vis\node_modules\io
broker.web\node_modules\letsencrypt\node_modules\rsa-compat\node_modules\ursa\b
uild\ursaNative.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
+++++++++++++++++++++++++++++++++++++++
 C:\Users\John\.node-red>npm install node-red-vis
|
> iobroker.vis-google-fonts@0.1.0 install C:\Users\John\.node-red\node_modules\node-red-vis\node_modules\iobroker.vis-google-fonts
> node main.js --install

> iobroker.vis@0.10.14 install C:\Users\John\.node-red\node_modules\node-red-vis\node_modules\iobroker.vis
> node main.js --install

> ursa@0.9.4 install C:\Users\John\.node-red\node_modules\node-red-vis\node_modules\iobroker.web\node_modules\letsencrypt\node_modules\rsa-compat\node_modules\ursa
> node-gyp rebuild

C:\Users\John\.node-red\node_modules\node-red-vis\node_modules\iobroker.web\node_modules\letsencrypt\node_modules\rsa-compat\node_modules\ursa>if not defined npm_config_n
ode_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  ursaNative.cc
  win_delay_load_hook.cc
c:\users\john\.node-gyp\4.6.0\include\node\v8.h(18): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory (compiling source file ..\src\urs
aNative.cc) [C:\Users\John\.node-red\node_modules\node-red-vis\node_modules\iobroker.web\node_modules\letsencrypt\node_modules\rsa-compat\node_modules\ursa\build\ursaNat
ive.vcxproj]
C:\Program Files (x86)\Windows Kits\8.1\Include\um\winnt.h(31): fatal error C1083: Cannot open include file: 'ctype.h': No such file or directory (compiling source file
C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.cc) [C:\Users\John\.node-red\node_modules\node-red-vis\node_modules\iobroker.web\n
ode_modules\letsencrypt\node_modules\rsa-compat\node_modules\ursa\build\ursaNative.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\John\.node-red\node_modules\node-red-vis\node_modules\iobroker.web\node_modules\letsencrypt\node_modules\rsa-compat\node_modules\ursa
gyp ERR! node -v v4.6.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN optional dep failed, continuing ursa@0.9.4

> node-red-vis@0.4.2 install C:\Users\John\.node-red\node_modules\node-red-vis
> node node_modules/iobroker.vis/lib/install.js

node-red-vis@0.4.2 node_modules\node-red-vis
├── iobroker.vis-keyboard@0.0.2
├── iobroker.vis-justgage@0.6.0
├── iobroker.vis-fancyswitch@1.0.0
├── iobroker.vis-bars@0.1.2
├── iobroker.vis-colorpicker@1.1.0
├── iobroker.vis-plumb@0.1.6
├── iobroker.vis-lcars@1.0.1
├── iobroker.vis-rgraph@0.0.2
├── iobroker.vis-metro@1.0.4
├── iobroker.vis-hqwidgets@1.0.6
├── socket.io@1.5.1 (has-binary@0.1.7, socket.io-parser@2.3.1, debug@2.2.0, socket.io-adapter@0.4.0, engine.io@1.7.2, socket.io-client@1.5.1)
├── iobroker.vis-jqui-mfd@1.0.5
├── iobroker.vis-timeandweather@1.1.4
├── iobroker.vis-google-fonts@0.1.0
├── iobroker.vis@0.10.14
└── iobroker.web@1.7.2 (connect-flash@0.1.1, xtend@4.0.1, passport.socketio@3.7.0, iobroker.socketio@1.7.1, iobroker.simple-api@1.3.0, cookie-parser@1.4.3, passport-local
@1.0.0, passport@0.3.2, express-session@1.14.2, body-parser@1.15.2, express@4.14.0, le-challenge-fs@2.0.8, le-sni-auto@2.1.0, le-store-certbot@2.0.3, request@2.78.0, lets
encrypt@2.1.8)

C:\Users\John\.node-red>

**Comment by GermanBluefox** [comment]
But as you can see, the dependency was optional and node-red-vis should anyway run.
