### ISSUE TITLE
LCARS vis question

### ISSUE THREAD

**Issue by marksev1** [GermanBluefox/node-red-vis#17]
How to set up toggle switch in LCARS UI, don't know if its a bug or something ->  https://github.com/ioBroker/ioBroker.vis-lcars/issues/4

Also how to set up the one that shows state? (value)

**Comment by GermanBluefox** [comment]
Please. Can you ask it on forum? 
http://forum.iobroker.net/viewforum.php?f=12
I am rather busy with ioBroker and sometimes need really much time to react.

P.S. ioBroker is not build **on** node-red. It is independent platform (very flexible) and can use node-red as scripting module (one of 5: node-red, javascript, scenes, Blockly, ScriptGUI).

Depends on your application I suggest you to use ioBroker too. Believe me, you will love it.

**Comment by marksev1** [comment]
I already tried but I can't create an account thats why I'm asking here.

**Comment by marksev1** [comment]
There is no progress here, when will you update npm?
