### ISSUE TITLE
Cannot edit views after running node-red with PM2?

### ISSUE THREAD

**Issue by maiorfi** [GermanBluefox/node-red-vis#5]
Hi.

I played with your amazing node-red-vis for a couple of hours.

After that, I re-installed node-red via npm install -g and similarly node-red-vis (i.e. via npm install -g), then configured node-red to be started at boot via PM2.

Since then, I couldn't edit views anymore: whatever I edit, I lose update at following refresh.

What could be most likely cause?

Thanks!

**Comment by maiorfi** [comment]
Solved by chmod 666 vis\* inside .node-red/vis/main

**Comment by GermanBluefox** [comment]
May be I should show an error if file cannot be saved. 
Thanks.
