### ISSUE TITLE
File not found error

### ISSUE THREAD

**Issue by RAGHAVNAIDU** [GermanBluefox/node-red-vis#7]
Hello there,

I am running node-red and node-red-vis under Ubuntu 14.04. I can run node-red without any errors. But I keep getting the following error. Please let me how I can solve this issue. 

GET http://xyz.com:1880/vis/_socket/info.js 
conn.js:222 socket.io not initialized
jquery-1.11.2.min.js:4 GET http://xyz.com:1880/vis.0/main/vis-user.css 404 (Not Found)m.ajaxTransport.send @ jquery-1.11.2.min.js:4m.extend.ajax @ jquery-1.11.2.min.js:4(anonymous function) @ vis.js:1562m.Callbacks.j @ jquery-1.11.2.min.js:2m.Callbacks.k.fireWith @ jquery-1.11.2.min.js:2m.extend.ready @ jquery-1.11.2.min.js:2J @ jquery-1.11.2.min.js:2
conn.js:486 Error: Cannot load /vis.0/main/vis-user.css - Not Found
conn.js:493 socket.io not initialized

**Comment by GermanBluefox** [comment]
Hello Ryan,
thank you for reporting the error.
Please update node-red-vis and it will be fixed.

BTW you can now write in any field the binding with variable, like
"{myNodeRed}"
Details can be found here:
https://www.npmjs.com/package/iobroker.vis#bindings-of-objects

Best Regards,
Bluefox

2015-05-06 21:38 GMT+02:00 Ryan notifications@github.com:

**Comment by RAGHAVNAIDU** [comment]
Thanks. Updating node-red-vis fixed the error.
