### ISSUE TITLE
Views incomplete or empty after update to 0.1.1

### ISSUE THREAD

**Issue by hermannw** [GermanBluefox/node-red-vis#8]
Today I decided to update to version 0.1.1. (npm update node-red-vis)
After I restarted node-red I tried to open as usual http://192.168.1.xx:1880/vis/index.html#metro but to my surprise I only got an empty page. Then I went to .../edit.html#metro. The editor opened, the tabs were there but everything was empty. After a while I noticed that when I click on the first tab (DemoView) I can see it's content and then I can click on the other tabs and see some things in there too. But most of the content is gone. 
The interesting thing is that I can see all the widgets in the "Active widgets" drop down list but not in the editor window. I have for instance four "Bulb on/off" widgets next to each other and I can see only one of them! When I drag a widget from the sidebar and drop it in the editor, it just disappears.

Any idea what went wrong?

P.S. Waht is the best way to get back to the previous version of node-red-vis? I have a backup from the night before. Can I just overwrite the "node-red-vis" folder?

Hermann

**Comment by GermanBluefox** [comment]
Hello Hermann,
there was an error yesterday and it was fixed at 20:00 13.05.15
You can just write
"_npm install --force_" in "_.../node_modules/node-red-vis_" directory and
you will get the new version of iobroker.vis.

Sorry for that. Too much optimized.

Bluefox

2015-05-14 3:07 GMT+02:00 hermannw notifications@github.com:

**Comment by hermannw** [comment]
Hi Bluefox,

that helped although I had to do it a bit different. Calling "npm install --force" inside the node-red-vis directory did nothing. So I went one level higher to the .../node-red directory and called "npm install --force node-red-vis". That did the trick.
Some more things I noticed after the update: 
- I am using 5 "Tile Toggle" widgets in my design. All their Object IDs were gone - although I could see them in the vis-views.json file.
- The "Active widgets" drop down list still shows "none selected" every now and then. When I click on a tab the drop down list shows the currently selected item. Then I click on a few other widgets and after about 5-8 clicks it changes to "none selected" and stays there until I select another tab.

Hermann

**Comment by GermanBluefox** [comment]
Hello Hermann,
Can you send me (over export function) your views or one view with problem
at dogafox at gmail.com?
I could check it.
Sometimes helps shift+F5 (cache erase)

Best regards,
Bluefox
14 Май 2015 г. 15:25 пользователь "hermannw" notifications@github.com
написал:

**Comment by hermannw** [comment]
If you are referring to the missing Object IDs, I solved that already. Like I said there were only 5 of them so I just added the IDs again.
As for the "none selected" widgets, it seems to happen only in Firefox. I am using Chrome right now and it works.
So I think we can consider this issue as solved!

Hermann
