### ISSUE TITLE
Tile Toggle not working after update to 0.2.0

### ISSUE THREAD

**Issue by hermannw** [GermanBluefox/node-red-vis#9]
Like the title says: After updating to version 0.2.0 the Tile Toggle does not work any longer.
And there is a difference between the "old" tile and the "new" one: 
The old tile that was there before the update, sends "true" as a payload to node-red every time it is clicked. The icon / color do not change.
If I place a "new" tile toggle from the sidebar and click on it, it sends "true" to node-red and the icon / color changes. On all subsequent clicks it sends "false" to node-red but the icon / color never changes.

![capture](https://cloud.githubusercontent.com/assets/5613181/8625802/90f9bf06-2706-11e5-999d-47a7e9d39a25.JPG)
Also there seems to be a problem with the border CSS. 
The first and second tile in the attached picture have both a border radius of 10px!
The third one has a border radius of 20px. All other values in "CSS Border" are empty. No matter what value I enter for border radius, the first tile always has smooth corners different from all the others...

Hermann

**Comment by hermannw** [comment]
Any ideas?

**Comment by GermanBluefox** [comment]
Can you still see an error?

**Comment by GermanBluefox** [comment]
And I can't reproduce your issue with radius. Can you export here the widgets?

Concerning Socket: it expects the new status from node-red. If you will send the same message to vis again, ot will change the color.
